"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const {forwardingPreview, hostRole, graphLayout} = require("../../viewer/viewer.js");
const model = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
const wire = model.wires[0];
const before = JSON.stringify(model);
assert.deepEqual(forwardingPreview(wire, "Gateway", "Uplink").outgoing, ["Gateway.Bus", "Gateway.Tail"]);
assert.match(forwardingPreview(wire, "Gateway", "Bypass").status, /Rejected/);
assert.deepEqual(forwardingPreview(wire, "LeafA", "Bus").outgoing, []);
assert.match(forwardingPreview(wire, "Observer", "Bus").status, /No route/);
assert.match(forwardingPreview({...wire, members:wire.members.filter(n => n !== "LeafA")}, "LeafA", "Bus").status, /no local delivery/);
assert.equal(hostRole(wire, "Gateway"), "transit");
assert.equal(hostRole(wire, "LeafB"), "member");
assert.equal(hostRole(wire, "Observer"), "excluded");
assert.match(forwardingPreview({...wire, resolved:false}, "Root", "").status, /Resolution failed/);
const physical = graphLayout(model, undefined, false);
assert.equal(physical.nodes.length, model.hosts.length + model.links.length);
const selected = graphLayout(model, wire, true);
assert.equal(selected.edges.length, wire.attachments.length);
assert(!selected.nodes.some(n => ["h:Observer", "l:Bypass"].includes(n.id)));
assert(selected.nodes.every(n => Number.isFinite(n.x) && Number.isFinite(n.y)));
assert.equal(new Set(selected.nodes.map(n => `${n.x}:${n.y}`)).size, selected.nodes.length);
assert.deepEqual(graphLayout(model, wire, true), selected);
assert.equal(JSON.stringify(model), before);
