"""Wire addressing and RAM limits shared by the Arduino UNO bench tools."""

NORMAL_BITS_CONTROL = 0x81
BACKGROUND_BITS_CONTROL = 0xC1
TEST_WIRE = 1
ARDUINO_HOST = 1
PC_HOST = 2
UPLOAD_ENDPOINT = 0x0001
ECHO_ENDPOINT = 0x0002
UNO_MAXIMUM_OBJECT_SIZE = 256
UNO_SEGMENT_SIZE = 24
