// Generated by codegen/wiring_codegen.py. Do not edit.
// Routes are local-origin masks; Router::receive validates and excludes the selected ingress.
#pragma once

#include <wirespaces/core/host.h>
#include <wirespaces/core/router.h>

namespace demo_wiring {

constexpr wirespaces::HostId kArduinoHost{1U};
constexpr wirespaces::HostId kPcHost{2U};
constexpr wirespaces::WireNumber kTestWire{1U};
constexpr wirespaces::EgressSet kUartEgress{0x01U};
constexpr std::uint8_t kUartIngressIndex{1U};
constexpr std::uint32_t kUartBaudRate{115200UL};
constexpr wirespaces::HostInfo kArduinoHostInfo{kArduinoHost, 1U, {kTestWire}};
constexpr wirespaces::RouteTableEntry kRoutes[]{
    {kTestWire, kUartEgress},
};

/** @brief Return the generated local-origin route table. */
inline wirespaces::foundation::Span<const wirespaces::RouteTableEntry> routes() noexcept {
    return {kRoutes};
}

/** @brief Fan out selected egress bits to application-owned Link forwarders. */
class Forwarder final : public wirespaces::PacketForwarder {
public:
    explicit Forwarder(wirespaces::PacketForwarder& link0) noexcept : link0_{link0} {}

    void forward(const wirespaces::PacketBuffer& packet, wirespaces::EgressSet selected) noexcept override {
        (void)packet;
        (void)selected;
        if ((selected & kUartEgress) != 0U) {
            link0_.forward(packet, kUartEgress);
        }
    }

private:
    wirespaces::PacketForwarder& link0_;  // Uart -> VcpUart
};

}  // namespace demo_wiring
