#!/usr/bin/env python3
"""Validate deployment YAML and generate static host wiring (requires PyYAML)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

CPP_KEYWORDS = set("""
alignas alignof and and_eq asm auto bitand bitor bool break case catch char char16_t
char32_t class compl const constexpr const_cast continue decltype default delete do
double dynamic_cast else enum explicit export extern false float for friend goto if
inline int long mutable namespace new noexcept not not_eq nullptr operator or or_eq
private protected public register reinterpret_cast return short signed sizeof static
static_assert static_cast struct switch template this thread_local throw true try
typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq
""".split())


from wiring_schema import SchemaLoader, require
from wiring_topology import resolve_deployment


def generate_header(data, *, namespace, header_name, local_host_name):
    deployment = resolve_deployment(data)
    hosts, links, wires = deployment.hosts, deployment.links, deployment.wires
    require(re.fullmatch(r"[a-zA-Z][a-zA-Z0-9_]*", namespace) is not None
            and "__" not in namespace and namespace not in CPP_KEYWORDS,
            "Invalid output namespace")
    require(local_host_name in hosts, f"Unknown local host: {local_host_name}")
    host = hosts[local_host_name]
    interfaces = sorted(host["Interfaces"], key=lambda i: i["EgressBit"])
    lines = [
        "// Generated by codegen/wiring_codegen.py. Do not edit.",
        "// Routes describe locally originated traffic; ingress-aware gateway routing is not provided.",
        "#pragma once", "", "#include <wirespaces/core/host.h>",
        "#include <wirespaces/core/router.h>", "", f"namespace {namespace} {{", "",
    ]
    symbols = set()

    def emit(symbol, declaration):
        require(symbol not in symbols, f"Generated identifier collision: {symbol}")
        symbols.add(symbol)
        lines.append(declaration)

    for h in sorted(hosts.values(), key=lambda h: h["Name"]):
        name = f"k{h['Name']}Host"
        emit(name, f"constexpr wirespaces::HostId {name}{{{h['HostId']}U}};")
    for w in sorted(wires.values(), key=lambda w: w["WireId"]):
        name = f"k{w['Name']}"
        emit(name, f"constexpr wirespaces::WireNumber {name}{{{w['WireId']}U}};")
    for i in interfaces:
        name = f"k{i['Name']}Egress"
        emit(name, f"constexpr wirespaces::EgressSet {name}{{0x{1 << i['EgressBit']:02X}U}};")
        link = links[i["Link"]]
        if "BaudRate" in link:
            name = f"k{i['Name']}BaudRate"
            emit(name, f"constexpr std::uint32_t {name}{{{link['BaudRate']}UL}};")
    members = sorted((w for w in wires.values() if local_host_name in w["Members"]), key=lambda w: w["WireId"])
    name = f"k{local_host_name}HostInfo"
    values = ", ".join(f"k{w['Name']}" for w in members)
    emit(name, f"constexpr wirespaces::HostInfo {name}{{k{local_host_name}Host, {len(members)}U, {{{values}}}}};")
    routes = []
    for w in sorted(wires.values(), key=lambda w: w["WireId"]):
        egresses = [f"k{i['Name']}Egress" for i in interfaces
                   if f"{local_host_name}.{i['Name']}" in w["Attachments"]]
        if egresses or w in members:
            mask = " | ".join(egresses) if egresses else "wirespaces::kNoEgress"
            routes.append(f"    {{k{w['Name']}, {mask}}},")
    if routes:
        emit("kRoutes", "constexpr wirespaces::RouteTableEntry kRoutes[]{")
        lines.extend(routes + ["};"])
    lines += ["", "/** @brief Return the generated local-origin route table. */",
              "inline wirespaces::foundation::Span<const wirespaces::RouteTableEntry> routes() noexcept {",
              "    return {kRoutes};" if routes else "    return {};",
              "}", "", "/** @brief Fan out selected egress bits to application-owned Link forwarders. */",
              "class Forwarder final : public wirespaces::PacketForwarder {", "public:"]
    args = ", ".join(f"wirespaces::PacketForwarder& link{i['EgressBit']}" for i in interfaces)
    init = ", ".join(f"link{i['EgressBit']}_{{link{i['EgressBit']}}}" for i in interfaces)
    lines += [f"    explicit Forwarder({args}) noexcept" + (f" : {init} {{}}" if init else " = default;"),
              "", "    void forward(const wirespaces::PacketBuffer& packet, wirespaces::EgressSet selected) noexcept override {",
              "        (void)packet;", "        (void)selected;"]
    for i in interfaces:
        mask = f"k{i['Name']}Egress"
        lines += [f"        if ((selected & {mask}) != 0U) {{",
                  f"            link{i['EgressBit']}_.forward(packet, {mask});", "        }"]
    lines += ["    }", "", "private:"]
    lines += [f"    wirespaces::PacketForwarder& link{i['EgressBit']}_;  // {i['Name']} -> {i['Link']}"
              for i in interfaces]
    lines += ["};", "", f"}}  // namespace {namespace}", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    output = parser.add_mutually_exclusive_group()
    output.add_argument("-o", "--output", type=Path)
    output.add_argument("--explain", action="store_true", help="Print resolved topology as JSON instead of C++")
    parser.add_argument("--local-host", required=True)
    parser.add_argument("--namespace", default="demo_wiring")
    args = parser.parse_args(argv)
    try:
        data = yaml.load(args.input.read_text(encoding="utf-8"), Loader=SchemaLoader)
        if args.explain:
            deployment = resolve_deployment(data)
            require(args.local_host in deployment.hosts, f"Unknown local host: {args.local_host}")
            print(json.dumps(deployment.explain(args.local_host), sort_keys=True, indent=2))
            return 0
        header = generate_header(data, namespace=args.namespace,
                                 header_name=args.output.name if args.output else "wiring.h",
                                 local_host_name=args.local_host)
        if args.output:
            args.output.write_text(header, encoding="utf-8")
        else:
            print(header, end="")
    except (ValueError, OSError, yaml.YAMLError) as error:
        parser.exit(2, f"wiring_codegen: {error}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
