#!/usr/bin/env python3
"""Validate deployment YAML and generate static host wiring (see requirements.txt)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

from wiring_inspection import explain_deployment
from wiring_models import AuthoredDeployment, TargetProjection
from wiring_projection import project_deployment
from wiring_schema import SchemaLoader, parse_deployment, require
from wiring_topology import resolve_deployment

CPP_KEYWORDS = set("""
alignas alignof and and_eq asm auto bitand bitor bool break case catch char char16_t
char32_t class compl const constexpr const_cast continue decltype default delete do
double dynamic_cast else enum explicit export extern false float for friend goto if
inline int long mutable namespace new noexcept not not_eq nullptr operator or or_eq
private protected public register reinterpret_cast return short signed sizeof static
static_assert static_cast struct switch template this thread_local throw true try
typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq
""".split())


def compile_deployment(data: AuthoredDeployment | dict) -> TargetProjection:
    """Run each compiler stage once; emitters only consume the target projection."""
    authored = data if isinstance(data, AuthoredDeployment) else parse_deployment(data)
    return project_deployment(resolve_deployment(authored))


def generate_header(data, *, namespace, header_name, local_host_name):
    """Compatibility entry point for callers supplying YAML data or an authored model."""
    return emit_header(compile_deployment(data), namespace=namespace, local_host_name=local_host_name)


def emit_header(projection: TargetProjection, *, namespace: str, local_host_name: str) -> str:
    """Emit C++ without performing topology resolution or egress assignment."""
    authored = projection.resolved.authored
    hosts, wires = authored.hosts, authored.wires
    require(re.fullmatch(r"[a-zA-Z][a-zA-Z0-9_]*", namespace) is not None
            and "__" not in namespace and namespace not in CPP_KEYWORDS,
            "Invalid output namespace")
    require(local_host_name in hosts, f"Unknown local host: {local_host_name}")
    host = projection.hosts[local_host_name]
    interfaces = host.interfaces
    lines = [
        "// Generated by codegen/wiring_codegen.py. Do not edit.",
        "// Routes are local-origin masks; Router::receive validates and excludes the selected ingress.",
        "#pragma once", "", "#include <wirespaces/core/host.h>",
        "#include <wirespaces/core/router.h>", "", f"namespace {namespace} {{", "",
    ]
    symbols = set()

    def emit(symbol, declaration):
        require(symbol not in symbols, f"Generated identifier collision: {symbol}")
        symbols.add(symbol)
        lines.append(declaration)

    for h in sorted(hosts.values(), key=lambda h: h.name):
        name = f"k{h.name}Host"
        emit(name, f"constexpr wirespaces::HostId {name}{{{h.host_id}U}};")
    for w in sorted(wires.values(), key=lambda w: w.wire_id):
        name = f"k{w.name}"
        emit(name, f"constexpr wirespaces::WireNumber {name}{{{w.wire_id}U}};")
    for i in interfaces:
        name = f"k{i.declaration.name}Egress"
        emit(name, f"constexpr wirespaces::InterfaceSet {name}{{0x{1 << i.egress_bit:02X}U}};")
        name = f"k{i.declaration.name}IngressIndex"
        emit(name, f"constexpr std::uint8_t {name}{{{i.ingress_index}U}};")
        if i.baud_rate is not None:
            name = f"k{i.declaration.name}BaudRate"
            emit(name, f"constexpr std::uint32_t {name}{{{i.baud_rate}UL}};")
        if i.can is not None:
            name = f"k{i.declaration.name}ArbitrationBitrate"
            emit(name, f"constexpr std::uint32_t {name}{{{i.can.arbitration_bitrate}UL}};")
            name = f"k{i.declaration.name}UseFdFrames"
            emit(name, f"constexpr bool {name}{{{str(i.can.fd_frames).lower()}}};")
            if i.can.fd_frames:
                name = f"k{i.declaration.name}BitRateSwitch"
                emit(name, f"constexpr bool {name}{{{str(i.can.bitrate_switch).lower()}}};")
            if i.can.data_bitrate is not None:
                name = f"k{i.declaration.name}DataBitrate"
                emit(name, f"constexpr std::uint32_t {name}{{{i.can.data_bitrate}UL}};")
    members = host.memberships
    name = f"k{local_host_name}HostInfo"
    values = ", ".join(f"k{w.name}" for w in members)
    emit(name, f"constexpr wirespaces::HostInfo {name}{{k{local_host_name}Host, {len(members)}U, {{{values}}}}};")
    routes = []
    for route in host.routes:
        egresses = [f"k{i.declaration.name}Egress" for i in interfaces if route.egress_mask & i.mask]
        mask = " | ".join(egresses) if egresses else "wirespaces::kNoEgress"
        routes.append(f"    {{k{route.wire.name}, {mask}}},")
    if routes:
        emit("kRoutes", "constexpr wirespaces::RouteTableEntry kRoutes[]{")
        lines.extend(routes + ["};"])
    lines += ["", "/** @brief Return the generated local-origin route table. */",
              "inline wirespaces::foundation::Span<const wirespaces::RouteTableEntry> routes() noexcept {",
              "    return {kRoutes};" if routes else "    return {};",
              "}", "", "/** @brief Fan out selected egress bits to application-owned Link forwarders. */",
              "class Forwarder final : public wirespaces::PacketForwarder {", "public:"]
    args = ", ".join(f"wirespaces::PacketLink& link{i.egress_bit}" for i in interfaces)
    init = ", ".join(f"link{i.egress_bit}_{{link{i.egress_bit}}}" for i in interfaces)
    lines += [f"    explicit Forwarder({args}) noexcept" + (f" : {init} {{}}" if init else " = default;"),
              "", "    wirespaces::RouteResult forward(const wirespaces::PacketBuffer& packet, wirespaces::InterfaceSet selected) noexcept override {",
              "        (void)packet;", "        (void)selected;", "        wirespaces::RouteResult result{wirespaces::RouteResult::kNoEgress};"]
    for i in interfaces:
        mask = f"k{i.declaration.name}Egress"
        lines += [f"        if ((selected & {mask}) != 0U) {{",
                  f"            result = wirespaces::combineAdmission(result, link{i.egress_bit}_.trySend(packet));", "        }"]
    lines += ["        return result == wirespaces::RouteResult::kNoEgress ? wirespaces::RouteResult::kAccepted : result;", "    }", "", "private:"]
    lines += [f"    wirespaces::PacketLink& link{i.egress_bit}_;  // {i.declaration.name} -> {i.declaration.link}"
              for i in interfaces]
    lines += ["};", "", f"}}  // namespace {namespace}", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    output = parser.add_mutually_exclusive_group()
    output.add_argument("-o", "--output", type=Path)
    output.add_argument("--explain", action="store_true", help="Print resolved topology as JSON instead of C++")
    parser.add_argument("--local-host", required=True)
    parser.add_argument("--namespace", default="demo_wiring")
    args = parser.parse_args(argv)
    try:
        data = yaml.load(args.input.read_text(encoding="utf-8"), Loader=SchemaLoader)
        if args.explain:
            projection = compile_deployment(data)
            print(json.dumps(explain_deployment(projection, args.local_host), sort_keys=True, indent=2))
            return 0
        header = generate_header(data, namespace=args.namespace,
                                 header_name=args.output.name if args.output else "wiring.h",
                                 local_host_name=args.local_host)
        if args.output:
            args.output.write_text(header, encoding="utf-8")
        else:
            print(header, end="")
    except (ValueError, OSError, yaml.YAMLError) as error:
        parser.exit(2, f"wiring_codegen: {error}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
